# ---
# spring:
#   profiles: default
#   datasource:
#     url: "jdbc:sqlite:file::memory:?cache=shared"
#     driver-class-name: org.sqlite.JDBC
#     initialization-mode: always
#     hikari:
#       maximum-pool-size: 1

---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/bookstore/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
